# Generated by Django 4.0 on 2022-05-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mail',
            field=models.EmailField(default='some_value', max_length=150),
        ),
    ]
